"""
commands/engineering.py — Engineering assistant commands for J.A.R.V.I.S.

Specializes in electronics, embedded systems, and digital design.
Generates code templates, explains circuits, and provides engineering references.

Domains:
- Verilog / VHDL
- Arduino / ESP32 / STM32
- FPGA (Quartus, Vivado)
- PCB Design (KiCad)
- Circuit analysis
- Signal processing
- Embedded C/C++
"""
import os
from core.logger import get_logger

log = get_logger("commands.engineering")


# ─── Verilog Templates ──────────────────────────────────

def _generate_verilog_module(name: str) -> str:
    """Generate a Verilog module template."""
    return f"""// {name}.v — Generated by J.A.R.V.I.S.
`timescale 1ns / 1ps

module {name} (
    input  wire clk,
    input  wire rst_n,
    input  wire [7:0] data_in,
    output reg  [7:0] data_out,
    output reg  valid
);

    // Internal signals
    reg [7:0] data_reg;

    // Sequential logic
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            data_reg <= 8'b0;
            data_out <= 8'b0;
            valid    <= 1'b0;
        end else begin
            data_reg <= data_in;
            data_out <= data_reg;
            valid    <= 1'b1;
        end
    end

endmodule
"""


def _generate_verilog_testbench(module_name: str) -> str:
    """Generate a Verilog testbench template."""
    return f"""// {module_name}_tb.v — Testbench generated by J.A.R.V.I.S.
`timescale 1ns / 1ps

module {module_name}_tb;

    // Signals
    reg        clk;
    reg        rst_n;
    reg  [7:0] data_in;
    wire [7:0] data_out;
    wire       valid;

    // DUT instantiation
    {module_name} uut (
        .clk      (clk),
        .rst_n    (rst_n),
        .data_in  (data_in),
        .data_out (data_out),
        .valid    (valid)
    );

    // Clock generation (50 MHz)
    initial clk = 0;
    always #10 clk = ~clk;

    // Test stimulus
    initial begin
        $dumpfile("{module_name}_tb.vcd");
        $dumpvars(0, {module_name}_tb);

        // Reset
        rst_n = 0;
        data_in = 8'h00;
        #100;
        rst_n = 1;

        // Test cases
        @(posedge clk);
        data_in = 8'hAA;
        @(posedge clk);
        data_in = 8'h55;
        @(posedge clk);
        data_in = 8'hFF;

        #200;
        $display("Test completed successfully");
        $finish;
    end

endmodule
"""


# ─── Arduino Templates ──────────────────────────────────

def _generate_arduino_sketch(name: str) -> str:
    """Generate an Arduino sketch template."""
    return f"""// {name}.ino — Generated by J.A.R.V.I.S.
// Arduino sketch template

#define LED_PIN 13
#define BAUD_RATE 115200

void setup() {{
    Serial.begin(BAUD_RATE);
    pinMode(LED_PIN, OUTPUT);

    Serial.println("{name} — Initialized");
    Serial.println("J.A.R.V.I.S. Arduino Template");
}}

void loop() {{
    // Blink LED
    digitalWrite(LED_PIN, HIGH);
    delay(500);
    digitalWrite(LED_PIN, LOW);
    delay(500);

    // Serial heartbeat
    Serial.print("Uptime: ");
    Serial.print(millis() / 1000);
    Serial.println("s");
}}
"""


# ─── ESP32 Templates ────────────────────────────────────

def _generate_esp32_sketch(name: str) -> str:
    """Generate an ESP32 sketch with WiFi template."""
    return f"""// {name}.ino — ESP32 sketch generated by J.A.R.V.I.S.
#include <WiFi.h>

const char* WIFI_SSID = "YOUR_SSID";
const char* WIFI_PASS = "YOUR_PASSWORD";

#define LED_PIN 2
#define BAUD_RATE 115200

void setup() {{
    Serial.begin(BAUD_RATE);
    pinMode(LED_PIN, OUTPUT);

    // Connect to WiFi
    Serial.print("Connecting to WiFi...");
    WiFi.begin(WIFI_SSID, WIFI_PASS);
    while (WiFi.status() != WL_CONNECTED) {{
        delay(500);
        Serial.print(".");
    }}
    Serial.println();
    Serial.print("Connected! IP: ");
    Serial.println(WiFi.localIP());
}}

void loop() {{
    if (WiFi.status() == WL_CONNECTED) {{
        digitalWrite(LED_PIN, HIGH);
    }} else {{
        digitalWrite(LED_PIN, LOW);
        WiFi.reconnect();
    }}
    delay(1000);
}}
"""


# ─── STM32 Templates ────────────────────────────────────

def _generate_stm32_main(name: str) -> str:
    """Generate an STM32 bare-metal main.c template."""
    return f"""// {name} — STM32 main.c generated by J.A.R.V.I.S.
#include "stm32f4xx.h"

void SystemClock_Config(void);
void GPIO_Init(void);
void Error_Handler(void);

int main(void) {{
    HAL_Init();
    SystemClock_Config();
    GPIO_Init();

    while (1) {{
        HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);  // Onboard LED
        HAL_Delay(500);
    }}
}}

void GPIO_Init(void) {{
    __HAL_RCC_GPIOA_CLK_ENABLE();

    GPIO_InitTypeDef GPIO_InitStruct = {{0}};
    GPIO_InitStruct.Pin = GPIO_PIN_5;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
}}

void Error_Handler(void) {{
    while (1) {{
        // Trap
    }}
}}
"""


# ─── VHDL Templates ─────────────────────────────────────

def _generate_vhdl_entity(name: str) -> str:
    """Generate a VHDL entity template."""
    return f"""-- {name}.vhd — Generated by J.A.R.V.I.S.
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity {name} is
    Port (
        clk      : in  STD_LOGIC;
        rst      : in  STD_LOGIC;
        data_in  : in  STD_LOGIC_VECTOR(7 downto 0);
        data_out : out STD_LOGIC_VECTOR(7 downto 0);
        valid    : out STD_LOGIC
    );
end {name};

architecture Behavioral of {name} is
    signal data_reg : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
begin
    process(clk, rst)
    begin
        if rst = '1' then
            data_reg <= (others => '0');
            data_out <= (others => '0');
            valid    <= '0';
        elsif rising_edge(clk) then
            data_reg <= data_in;
            data_out <= data_reg;
            valid    <= '1';
        end if;
    end process;
end Behavioral;
"""


# ─── File Generation ────────────────────────────────────

def _save_generated_file(content: str, filename: str) -> tuple[bool, str]:
    """Save generated code to a file on the Desktop."""
    try:
        desktop = os.path.join(os.path.expanduser("~"), "Desktop")
        filepath = os.path.join(desktop, filename)
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        log.info("Generated file: %s", filepath)
        return True, f"File saved to Desktop: {filename}"
    except Exception as e:
        log.error("File generation failed: %s", e)
        return False, f"Failed to save file: {e}"


# ─── Quick References ───────────────────────────────────

ENGINEERING_REFERENCES = {
    "mosfet": "MOSFET: Metal-Oxide-Semiconductor Field-Effect Transistor. "
              "N-channel conducts when gate voltage > threshold. P-channel is complementary. "
              "Key params: Vth (threshold), Rds_on (resistance), Id_max (max drain current).",

    "cmos": "CMOS: Complementary MOS. Uses pairs of NMOS and PMOS transistors. "
            "Zero static power consumption. Key building blocks: inverter, NAND, NOR. "
            "Power = dynamic (CV²f) + static (leakage).",

    "vlsi": "VLSI: Very Large Scale Integration. Design flow: Spec → RTL → Synthesis → "
            "Place & Route → DRC/LVS → Tapeout. Tools: Synopsys, Cadence, Mentor.",

    "fpga": "FPGA: Field-Programmable Gate Array. Contains CLBs, IOBs, and routing. "
            "Vendors: Xilinx (Vivado), Intel/Altera (Quartus). HDLs: Verilog, VHDL, SystemVerilog.",

    "uart": "UART: Universal Asynchronous Receiver-Transmitter. "
            "Standard baud rates: 9600, 115200. Frame: start bit + 8 data + optional parity + stop bit.",

    "spi": "SPI: Serial Peripheral Interface. 4 wires: MOSI, MISO, SCK, CS. "
           "Full-duplex, master-slave. Modes 0-3 (CPOL/CPHA). No addressing — uses chip select.",

    "i2c": "I2C: Inter-Integrated Circuit. 2 wires: SDA, SCL. "
           "Multi-master, multi-slave with 7-bit addressing. Speeds: 100kHz, 400kHz, 3.4MHz.",

    "pcb": "PCB Design Flow: Schematic → Footprint assignment → Board layout → "
           "Routing → DRC → Gerber export. Tools: KiCad (free), Altium, Eagle.",

    "adc": "ADC: Analog-to-Digital Converter. Types: SAR (fast, common), "
           "Sigma-Delta (high resolution), Flash (fastest, expensive). Resolution in bits, "
           "sampling rate in SPS.",

    "dac": "DAC: Digital-to-Analog Converter. Types: R-2R ladder, binary weighted, "
           "current steering. Resolution in bits. Used for audio, control signals.",
}


# ─── Command Router ─────────────────────────────────────

def handle_engineering_command(command: str) -> tuple[bool, bool, str]:
    """
    Route engineering-related commands.

    Returns:
        (handled, success, message)
    """
    cmd = command.lower().strip()

    # ─── Code Generation ────────────────────────
    if cmd.startswith("generate verilog ") or cmd.startswith("create verilog "):
        name = cmd.replace("generate verilog ", "").replace("create verilog ", "").strip()
        if not name:
            name = "my_module"
        name = name.replace(" ", "_")
        code = _generate_verilog_module(name)
        ok, msg = _save_generated_file(code, f"{name}.v")
        return True, ok, msg

    if cmd.startswith("generate testbench ") or cmd.startswith("create testbench "):
        name = cmd.replace("generate testbench ", "").replace("create testbench ", "").strip()
        if not name:
            name = "my_module"
        name = name.replace(" ", "_")
        code = _generate_verilog_testbench(name)
        ok, msg = _save_generated_file(code, f"{name}_tb.v")
        return True, ok, msg

    if cmd.startswith("generate vhdl ") or cmd.startswith("create vhdl "):
        name = cmd.replace("generate vhdl ", "").replace("create vhdl ", "").strip()
        if not name:
            name = "my_entity"
        name = name.replace(" ", "_")
        code = _generate_vhdl_entity(name)
        ok, msg = _save_generated_file(code, f"{name}.vhd")
        return True, ok, msg

    if cmd.startswith("generate arduino ") or cmd.startswith("create arduino "):
        name = cmd.replace("generate arduino ", "").replace("create arduino ", "").strip()
        if not name:
            name = "my_sketch"
        name = name.replace(" ", "_")
        code = _generate_arduino_sketch(name)
        ok, msg = _save_generated_file(code, f"{name}/{name}.ino")
        return True, ok, msg

    if cmd.startswith("generate esp32 ") or cmd.startswith("create esp32 "):
        name = cmd.replace("generate esp32 ", "").replace("create esp32 ", "").strip()
        if not name:
            name = "esp32_project"
        name = name.replace(" ", "_")
        code = _generate_esp32_sketch(name)
        ok, msg = _save_generated_file(code, f"{name}/{name}.ino")
        return True, ok, msg

    if cmd.startswith("generate stm32 ") or cmd.startswith("create stm32 "):
        name = cmd.replace("generate stm32 ", "").replace("create stm32 ", "").strip()
        if not name:
            name = "stm32_project"
        name = name.replace(" ", "_")
        code = _generate_stm32_main(name)
        ok, msg = _save_generated_file(code, f"{name}/main.c")
        return True, ok, msg

    # ─── Quick References ───────────────────────
    if cmd.startswith(("explain ", "what is a ", "what is ")):
        topic = (cmd.replace("explain ", "")
                 .replace("what is a ", "")
                 .replace("what is ", "").strip())
        ref = ENGINEERING_REFERENCES.get(topic)
        if ref:
            return True, True, ref

    # ─── Reference lookups ──────────────────────
    for topic, ref in ENGINEERING_REFERENCES.items():
        if topic in cmd and len(cmd) < 40:
            return True, True, ref

    return False, False, ""
